BUFFER_SIZE = 1024
INITIAL_SIZE = 4096
CLIENT_ROOT_PATH = "client_files\\"
STORAGE_ROOT_PATH = "storage_server"
SERVER_ROOT_PATH = "C:\\Repositories\\DFS\\"
NAMING_SERVER_IP = "localhost"
NAMING_SERVER_PORT = 8800
STORAGE_SERVER_PORT = 8801
