FROM python:3.7.4

WORKDIR /app

EXPOSE 8801

ADD . .

RUN apt-get update && apt-get install -y --no-install-recommends gettext && apt-get clean && apt install python3 && pip3 install requests

CMD python3 storage_server.py
