FROM python:3.7.4

WORKDIR /app

EXPOSE 8800

ADD . .

RUN apt-get update && apt-get install -y --no-install-recommends gettext && apt-get clean && pip3 install requests

CMD python naming_server.py

